spring.application.name=notes-api

server.port=8081

spring.datasource.url=jdbc:mysql://localhost:3306/notesdb
spring.datasource.username=aku
spring.datasource.password=Aku1!

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true